import { ModelComplete } from "@/core/core.interface";
import { CustomersResource } from "./customers.interface";

const ROUTE = "clientes";

export const CUSTOMERS: ModelComplete<CustomersResource> = {
  MODEL: {
    name: "Cliente",
    plural: "Clientes",
    gender: false,
  },
  ICON: "ContactRound",
  ENDPOINT: "/ap/commercial/businessPartners",
  QUERY_KEY: "customers",
  ROUTE,
  ROUTE_ADD: `${ROUTE}/agregar`,
  ROUTE_UPDATE: `${ROUTE}/actualizar`,
  EMPTY: {
    id: 0,
    first_name: "",
    middle_name: "",
    paternal_surname: "",
    maternal_surname: "",
    full_name: "",
    birth_date: "",
    nationality: "",
    num_doc: "",
    spouse_num_doc: null,
    spouse_full_name: null,
    direction: "",
    legal_representative_num_doc: null,
    legal_representative_name: null,
    legal_representative_paternal_surname: null,
    legal_representative_maternal_surname: null,
    legal_representative_full_name: null,
    email: "",
    secondary_email: null,
    phone: "",
    secondary_phone: null,
    secondary_phone_contact_name: null,
    driver_num_doc: null,
    driver_full_name: null,
    driving_license: null,
    driving_license_expiration_date: "",
    company_status: "",
    company_condition: "",
    origin_id: "",
    tax_class_type_id: "",
    type_person_id: "",
    district_id: "",
    document_type_id: "",
    person_segment_id: "",
    marital_status_id: "",
    gender_id: "",
    activity_economic_id: "",
    company_id: 0,
    type: "",
    driving_license_category: null,
  },
};
