export const COMMERCIAL_MASTERS_ENDPOINT = "/ap/commercialMasters";

export const POSTVENTA_MASTERS_ENDPOINT = "/ap/postVentaMasters";

export const AP_MASTER_COMERCIAL = {
  VEHICLE_CATEGORY: "CATEGORIA_VEHICULO",
  VEHICLE_COLOR: "COLOR_VEHICULO",
  GROUP_BRANDS: "GRUPO_MARCAS",
  VEHICLE_ORIGIN: "ORIGEN_VEHICULO",
  VEHICLE_TYPE: "TIPO_VEHICULO",
  BODY_TYPE: "TIPO_CARROCERIA",
  ENGINE_TYPE: "TIPO_MOTOR",
  SUPPLIER_ORDER_TYPE: "TIPO_PEDIDO_PROVEEDOR",
  TRACTION_TYPE: "TIPO_TRACCION",
  PRODUCT_TYPE: "TIPO_PRODUCTO",
  CATEGORIA_CHECKLIST: "CATEGORIA_CHECKLIST",
  TRANSMISION_VEHICLE: "TRANSMISION_VEHICULO",
  BANK: "BANCO",
  ACCOUNTING_ACCOUNT_TYPE: "TIPO_CUENTA_CONTABLE",
  CLIENT_ORIGIN: "ORIGEN_CLIENTE",
  ECONOMIC_ACTIVITY: "ACTIVIDAD_ECONOMICA",
  TYPE_PERSON: "TIPO_PERSONA",
  MARITAL_STATUS: "ESTADO_CIVIL",
  TYPE_GENDER: "TIPO_SEXO",
  VOUCHER_TYPE: "TIPO_COMPROBANTE",
  TYPE_OPERATION: "TIPO_OPERACION",
  SHOP: "TIENDA",
  DOCUMENT_TYPE: "TIPO_DOCUMENTO",
  PERSON_SEGMENT: "SEGMENTO_PERSONA",
  INCOME_SECTOR: "SECTOR_INGRESO",
  REASONS_REJECTION: "MOTIVOS_DESCARTE",
};

export const AP_MASTER_POST_VENTA = {
  TYPE_CATEGORY: "TIPO_CATEGORIA",
  TYPE_ADJUSTMENT_IN: "ADJUSTMENT_IN",
  TYPE_ADJUSTMENT_OUT: "ADJUSTMENT_OUT",
  TRANSFER_OUT: "TRANSFER_OUT",
  TYPE_PLANNING: "TIPO_PLANIFICACION",
  TYPE_OPERACTION_APPOINTMENT: "TIPO_OPERACION",
};
