import { type ModelComplete } from "@/core/core.interface";
import { ApMastersResource } from "./apMasters.interface";

const ROUTE = "maestros-generales";
const ABSOLUTE_ROUTE = `/ap/comercial/${ROUTE}`;

export const AP_MASTERS: ModelComplete<ApMastersResource> = {
  MODEL: {
    name: "Ap Maestro",
    plural: "Ap Maestros",
    gender: true,
  },
  ICON: "Database",
  ENDPOINT: "/ap/apMasters",
  QUERY_KEY: "apMastersGenerales",
  ROUTE,
  ABSOLUTE_ROUTE,
  ROUTE_ADD: `${ABSOLUTE_ROUTE}/agregar`,
  ROUTE_UPDATE: `${ABSOLUTE_ROUTE}/actualizar`,
  EMPTY: {
    id: 0,
    code: "",
    description: "",
    type: "",
    status: true,
  },
};

export const AP_MASTER_TYPE = {
  VEHICLE_CATEGORY: "CATEGORIA_VEHICULO",
  VEHICLE_COLOR: "COLOR_VEHICULO",
  GROUP_BRANDS: "GRUPO_MARCAS",
  VEHICLE_ORIGIN: "ORIGEN_VEHICULO",
  VEHICLE_TYPE: "TIPO_VEHICULO",
  BODY_TYPE: "TIPO_CARROCERIA",
  ENGINE_TYPE: "TIPO_MOTOR",
  SUPPLIER_ORDER_TYPE: "TIPO_PEDIDO_PROVEEDOR",
  TRACTION_TYPE: "TIPO_TRACCION",
  PRODUCT_TYPE: "TIPO_PRODUCTO",
  CATEGORIA_CHECKLIST: "CATEGORIA_CHECKLIST",
  TRANSMISION_VEHICLE: "TRANSMISION_VEHICULO",
  BANK: "BANCO",
  ACCOUNTING_ACCOUNT_TYPE: "TIPO_CUENTA_CONTABLE",
  CLIENT_ORIGIN: "ORIGEN_CLIENTE",
  ECONOMIC_ACTIVITY: "ACTIVIDAD_ECONOMICA",
  TYPE_PERSON: "TIPO_PERSONA",
  MARITAL_STATUS: "ESTADO_CIVIL",
  TYPE_GENDER: "TIPO_SEXO",
  VOUCHER_TYPE: "TIPO_COMPROBANTE",
  TYPE_OPERATION: "TIPO_OPERACION",
  SHOP: "TIENDA",
  DOCUMENT_TYPE: "TIPO_DOCUMENTO",
  PERSON_SEGMENT: "SEGMENTO_PERSONA",
  INCOME_SECTOR: "SECTOR_INGRESO",
  REASONS_REJECTION: "MOTIVOS_DESCARTE",
  // TYPES POST VENTA
  PRODUCT_CATEGORY: "CATEGORIA_PRODUCTO",
  TYPE_ADJUSTMENT_IN: "ADJUSTMENT_IN",
  TYPE_ADJUSTMENT_OUT: "ADJUSTMENT_OUT",
  TRANSFER_OUT: "TRANSFER_OUT",
  TYPE_PLANNING: "TIPO_PLANIFICACION",
  TYPE_OPERACTION_APPOINTMENT: "TIPO_OPERACION_CITA",
  DISCARDING_SPAREPART: "MOTIVO_DESCARTE_REPUESTO",
};

export const AREA_CM_ID = {
  COMERCIAL: "826",
  POSTVENTA: "825",
};

export const AREA_PM_ID = {
  TALLER: "881",
  MESON: "882",
};

export const ON_SELECT_AREA = [
  { label: "COMERCIAL", value: AREA_CM_ID.COMERCIAL },
  { label: "POSTVENTA", value: AREA_CM_ID.POSTVENTA },
];

// ESTADOS DE ORDEN DE TRABAJO
export const OPENING_WORK_ORDER_ID = 884;
export const RECEIVED_WORK_ORDER_ID = 889;
export const AT_WORK_WORK_ORDER_ID = 890;
export const FINISHED_WORK_ORDER_ID = 891;
export const CLOSED_WORK_ORDER_ID = 892;
export const CANCELED_WORK_ORDER_ID = 893;
