import { type ModelComplete } from "@/core/core.interface";
import { SunatConceptsResource } from "./sunatConcepts.interface";

const ROUTE = "conceptos-sunat";
const ABSOLUTE_ROUTE = `/gp/maestro-general/${ROUTE}`;

export const SUNAT_CONCEPTS: ModelComplete<SunatConceptsResource> = {
  MODEL: {
    name: "Concepto SUNAT",
    plural: "Conceptos SUNAT",
    gender: true,
  },
  ICON: "ContactRound",
  ENDPOINT: "/gp/mg/sunatConcepts",
  QUERY_KEY: "commercialMasters",
  ROUTE,
  ABSOLUTE_ROUTE,
  ROUTE_ADD: `${ABSOLUTE_ROUTE}/agregar`,
  ROUTE_UPDATE: `${ABSOLUTE_ROUTE}/editar`,
};

export const SUNAT_CONCEPTS_TYPE = {
  TYPE_DOCUMENT: "TYPE_DOCUMENT",
  TYPE_VOUCHER: "TYPE_VOUCHER",
  TRANSFER_REASON: "TRANSFER_REASON",
  TYPE_TRANSPORTATION: "TYPE_TRANSPORTATION",
  BILLING_DOCUMENT_TYPE: "BILLING_DOCUMENT_TYPE",
  BILLING_TRANSACTION_TYPE: "BILLING_TRANSACTION_TYPE",
  TYPE_DOCUMENT_IDENTITIES: "TYPE_DOCUMENT_IDENTITIES",
  BILLING_CURRENCY: "BILLING_CURRENCY",
  BILLING_IGV_TYPE: "BILLING_IGV_TYPE",
  BILLING_DETRACTION_TYPE: "BILLING_DETRACTION_TYPE",
  BILLING_CREDIT_NOTE_TYPE: "BILLING_CREDIT_NOTE_TYPE",
  BILLING_DEBIT_NOTE_TYPE: "BILLING_DEBIT_NOTE_TYPE",
};

export const SUNAT_CONCEPTS_ID = {
  TRANSFER_REASON_COMPRA: "15",
  TRANSFER_REASON_TRASLADO_SEDE: "17",
  TRANSFER_REASON_OTROS: "23",
  TYPE_TRANSPORTATION_PRIVATE: "28",
  TYPE_TRANSPORTATION_PUBLIC: "27",
};

export const SUNAT_TYPE_INVOICES_ID = {
  FACTURA: 29,
  BOLETA: 30,
  NOTA_CREDITO: 31,
  NOTA_DEBITO: 32,
};

export const SUNAT_TRANSACTIONS_ID = {
  VENTA_INTERNA: 33,
  ANTICIPOS: 36,
};
