import { type ModelComplete } from "@/core/core.interface";
import { SuppliersResource } from "./suppliers.interface";

const ROUTE = "proveedores";

export const SUPPLIERS: ModelComplete<SuppliersResource> = {
  MODEL: {
    name: "Proveedor",
    plural: "Proveedores",
    gender: true,
  },
  ICON: "ContactRound",
  ENDPOINT: "/ap/commercial/businessPartners",
  QUERY_KEY: "suppliers",
  ROUTE,
  ROUTE_ADD: `./agregar`,
  ROUTE_UPDATE: `./actualizar`,
  EMPTY: {
    id: 0,
    first_name: "",
    middle_name: "",
    paternal_surname: "",
    maternal_surname: "",
    full_name: "",
    num_doc: "",
    spouse_num_doc: null,
    spouse_full_name: null,
    direction: "",
    email: "",
    secondary_email: null,
    phone: "",
    secondary_phone: null,
    secondary_phone_contact_name: null,
    company_status: "",
    company_condition: "",
    supplier_tax_class_id: "",
    type_person_id: "",
    district_id: "",
    document_type_id: "",
    person_segment_id: "",
    company_id: 0,
    type: "",
    legal_representative_num_doc: null,
    legal_representative_name: null,
    legal_representative_paternal_surname: null,
    legal_representative_maternal_surname: null,
    legal_representative_full_name: null,
    birth_date: null,
    nationality: "",
    driver_num_doc: null,
    driver_full_name: null,
    driving_license: null,
    driving_license_expiration_date: null,
    status_license: null,
    restriction: null,
    origin_id: null,
    driving_license_category: null,
    tax_class_type_id: 0,
    marital_status_id: null,
    gender_id: null,
    activity_economic_id: null,
    origin: null,
    supplier_tax_class_type: undefined,
    tax_class_type: undefined,
    type_road: null,
    type_person: "",
    district: "",
    document_type: "",
    person_segment: "",
    marital_status: null,
    gender: null,
    activity_economic: null,
    company: "",
  },
};
